coaching/coach/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.contrib import admin

app_name = "coach"

urlpatterns = [
    path("", views.home, name="home"),
    
    path("signin", views.signin, name="signin"),
    path("signup", views.signup, name="signup"),
    path("logout", views.sign_out, name="logout"),

    path("session", views.session, name="session"),
    path('products/', views.session_filtre, name='session_filtre'),
    path("shop", views.shop, name="shop"),
    path("products/<int:id>", views.products, name="products"),
    path('products_list', views.product_list, name='product_list'),
    

    path("session_creation", views.session_creation, name="session_creation"),
    path("update_session", views.update_session, name="update_session"),
    path("addimg", views.add_session, name="addimg"),
    path("updateimg", views.update_session_img, name="updateimg"),


    path("cart", views.cart, name="cart"),
    path(
        "cart/update_item_quantity",
        views.update_item_quantity,
        name="update_item_quantity",
    ),
    path("cart/add_to_cart", views.add_to_cart, name="add_cart_item"),
    path(
        "cart/add_order",
        views.add_order_handler,
        name="add_order",
    ),
    path(
        "cart/delete_cart_item", views.delete_cart_item_handler, name="delete_cart_item"
    ),
    path("add_to_cart_popup/<int:session_id>/", views.pop_up, name="add_to_cart_popup"),
    path("reviews/<int:session_id>/", views.reviews, name="reviews"),
    path("comments/<int:session_id>/", views.get_sessions_reviews, name="comments"),


    path("dashboard", views.dashboard, name="dashboard"),
    path("delete-session/<int:session_id>/", views.delete_session, name="delete_session"),
    path("stats", views.stats, name="stats"),
    path("stats/participent_by_coach", views.participent_by_coach, name="participent_by_coach"),
    path("stats/revenue_by_session", views.revenue_by_session, name="revenue_by_session"),
    path("stats/top_sessions", views.top_sessions, name="top_sessions"),
    path("profile", views.profile, name="profile"),
    path("profile/coach_request", views.coach_request, name="coach_request"),
    path("delete-session-order/<int:order_id>/", views.delete_session_order, name="delete_order_session"),
]


# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coaching/coaching/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("coach.urls")),
]

coaching/coach/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

import random

def generate_random_id():
    return random.randint(10000, 99999)  # Adjust the range as needed



class Profile(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/',default="profile2.png")

    class Type(models.TextChoices):
        Client = 'client'
        Coache = 'coach'

    def __str__(self):
        return f"{self.type} - id {self.id}"
    type = models.CharField(max_length=7, choices=Type.choices, default=Type.Client)


class session_location(models.Model):
    id = models.AutoField(primary_key=True)
    location = models.CharField(max_length=100, null=True)
    


class Training_session(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True)
    small_sum = models.CharField(max_length=100, null=True)
    categorie = models.CharField(max_length=100, null=True)
    type = models.CharField(max_length=100, null=True)
    description = models.JSONField( null=True)
    price = models.DecimalField( max_digits=5, decimal_places=2, null=True)
    Profile = models.ForeignKey(Profile, on_delete=models.CASCADE,default=1) 
    img = models.ImageField(upload_to="sessions/%y/%m/%d", null=True)
    start_time = models.TimeField(null=True)    
    end_time = models.TimeField(null=True)   
    participant_limit = models.IntegerField(null=True)
    location = models.ForeignKey(session_location,default='1', on_delete=models.CASCADE)

class categorie(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True)

    
    
    
    
class session_date(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateField(null=True)
    session = models.ForeignKey(Training_session, on_delete=models.CASCADE)

    

class Reviews(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    session = models.ForeignKey(Training_session, on_delete=models.CASCADE)
    stars = models.IntegerField()
    comment = models.TextField(blank=True, null=True)
    title = models.TextField(blank=True, null=True)




class Product(models.Model):
    id = models.AutoField(primary_key=True)
    description = models.TextField(null=True)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=50, null=True)

    def __str__(self):
        return f"{self.name} - Id {self.id}"

class ProductImages(models.Model):
    id = models.AutoField(primary_key=True)
    urls = models.ImageField(upload_to="products/%y/%m/%d")
    type = models.CharField(max_length=50)

    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    #convertir un objet en chaîne de caractères
    def __str__(self):
        return f"{self.product.name} - Image {self.urls}"

class ProductVariant(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    product = models.ForeignKey("Product", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name} - Variant {self.id}"

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    address = models.TextField()
    order_total = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart_name = models.CharField(max_length=255)
    exp = models.DateField()
    cvv = models.CharField(max_length=4)
    

    def __str__(self):
        return f"Order {self.id} - {self.first_name} {self.last_name} - Total: {self.order_total}"

class OrderToProduct(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey("Order", on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.SET_NULL,related_name='orders_product', null=True, blank=True)
    training_session = models.ForeignKey("Training_session",related_name='orders_training_session',on_delete=models.CASCADE, null=True, blank=True)
    product_name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    price=models.DecimalField(max_digits=10, decimal_places=2, default=0)
    type = models.CharField(max_length= 255, default="session")
    date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return f"Order {self.order_id} - {self.product_name} - Quantity {self.quantity}"

class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)



    def __str__(self):
        return f"Cart {self.id} - Total: {self.total}"

class CartItem(models.Model):
    id = models.AutoField(primary_key=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    cart_id = models.ForeignKey("Cart", on_delete=models.CASCADE)
    product = models.ForeignKey("Product",on_delete=models.SET_NULL, null=True, blank=True)
    training_session = models.ForeignKey("Training_session",on_delete=models.SET_NULL, null=True, blank=True)
    type = models.CharField(max_length= 255, default="session")

    #chose what to display in admin 
    def __str__(self):
        return f"CartItem {self.id} - Quantity: {self.quantity} - Price: {self.price}"
    

class CoachRequest(models.Model):
    id = models.AutoField(primary_key=True)
    exp = models.CharField(max_length= 255, default="1")
    description= models.CharField(max_length= 255, default="")
    Profile = models.ForeignKey(Profile, on_delete=models.CASCADE,default=1) 
    
    def __str__(self):
        return f"REQUEST {self.id} - experience: {self.exp}"

coaching/coach/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Training_session,Profile,CoachRequest


class SigninForm(forms.Form):
        email = forms.EmailField(required=True)
        password = forms.CharField(max_length=50)  
        

class SignupForm(UserCreationForm):
    firstname = forms.CharField(max_length=50)
    lastname = forms.CharField(max_length=50)
    email=forms.EmailField(required=True)
    class Meta:
        model=User
        fields=['username','email','password1','password2']
    def save(self, commit=True):
        user = super(SignupForm , self).save(commit=False)
        user.first_name = self.cleaned_data["firstname"]
        user.last_name = self.cleaned_data["lastname"]
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]

        if commit:
            print("user-commit")
            print(user)
            user.save()
        return user
    
class ImageForm(forms.ModelForm):
    class Meta:
        model = Training_session        
        fields = ['Profile', 'img']  # Include 'user' field in the form
    
          
class sessionform(forms.ModelForm):
    class Meta:
        model = Training_session        
        fields = ['description', 'name', 'start_time', 'end_time']  # Include 'user' field in the form


    # id = models.AutoField(primary_key=True)
    # name = models.CharField(max_length=100, null=True)
    # description = models.CharField(max_length=100, null=True)
    # Profile = models.ForeignKey(Profile, on_delete=models.CASCADE) 
    # img = models.ImageField(upload_to="sessions/%y/%m/%d", null=True)
    # start_time = models.DateTimeField(null=True)    
    # end_time = models.DateTimeField(null=True)   
    # location = models.CharField(max_length=100,null=True)
    # participant_limit = models.IntegerField(null=True) 

class FilterForm(forms.Form):
    PRICE_CHOICES = [
        ('under_25', 'Under $25'),
        ('25_to_50', '$25 to $50'),
        ('50_to_100', '50 to $100'),
        ('over_100', 'Over $100'),
    ]
    SORT_CHOICES = [
        ('popularity', 'Popularity'),
        ('high_to_low', 'Price: High to Low'),
        ('low_to_high', 'Price: Low to High'),
    ]
    SESSION_TYPE_CHOICES = [
        ('Personal', 'Personal'),
        ('Group', 'Group'),
    ]
    
    price_range = forms.ChoiceField(
        choices=PRICE_CHOICES,
        widget=forms.RadioSelect,
        required=False
    )
    sort_by = forms.ChoiceField(
        choices=SORT_CHOICES,
        widget=forms.RadioSelect,
        required=False
    )
    session_type = forms.ChoiceField(
        choices=SESSION_TYPE_CHOICES,
        widget=forms.RadioSelect,
        required=False
    )


class Editprofileform(forms.ModelForm):

    class Meta:
        model=User
        fields=['first_name','last_name']

class Editimageprofileform(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        
        
class coach_request_form(forms.ModelForm):
    class Meta:
        model = CoachRequest
        fields = ['exp','description','Profile']

coaching/coach/views.py
from coach.api.sign_up import signup
from coach.api.home import home
from coach.api.sign_in import signin
from coach.api.logout import sign_out
from coach.api.session import session
from coach.api.shop import shop
from coach.api.products import products
from coach.api.training_session.create_session import add_session,update_session_img
from coach.api.update_session import update_session
from coach.api.productslist import product_list
from coach.api.cart import cart
from coach.api.add_to_cart import add_to_cart
from coach.api.dashboard import dashboard
from coach.api.session_creation import session_creation
from coach.api.delete_cart_item import delete_cart_item_handler
from coach.api.add_order import add_order_handler
from coach.api.profile import profile,coach_request
from coach.api.stats import stats,participent_by_coach,revenue_by_session,top_sessions
from coach.api.session_filtrage import session_filtre
from coach.api.add_to_cart_popup import pop_up
from coach.api.reviews import reviews,get_sessions_reviews
from coach.api.update_item_quantity import update_item_quantity
from coach.api.delete_session_order import delete_session_order

from coach.api.delete_session import delete_session

coaching/coach/templates/coach/products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>

		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
		<link href="https://api.fontshare.com/v2/css?f[]=clash-display@400,500,700&display=swap" rel="stylesheet">

		{% comment %} external links {% endcomment %}
		<link
		rel="stylesheet"
		href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,200"
		/>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;500;600;700&display=swap"
			rel="stylesheet"
		/>
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

		{% comment %} local links {% endcomment %}
		<link rel="stylesheet" href="{% static 'coach/nav.css' %}" />
		<link rel="stylesheet" href="{% static 'coach/global.css' %}" />
		
	</head>
	<body>
		{% include 'coach/componants/nav.html' %}
		<main class="w-full mx-auto mt-44 ">
			<div
				class="max-w-[1400px] mx-auto w-full flex h-full items-center justify-between"
			>
					<div
						data-hs-carousel='{
						"loadingClasses": "opacity-0"
						}'
						class="relative w-[700px] "
						>
						<div class="hs-carousel relative overflow-hidden w-full min-h-[500px]">
							<div
							class="hs-carousel-body absolute top-0 bottom-0 start-0 flex flex-nowrap transition-transform duration-700 opacity-0"
							>
							{% for p in product.imgs.all %}
								<img
									src="{{MEDIA_URL}}{{p.urls}}"
									class="hs-carousel-slide bg-green-900 object-cover"
								/>
							{% endfor %}
							</div>
							
						</div>

						<div class="flex w-full justify-center gap-x-3 items-center mt-5">
							<button type="button" class="hs-carousel-prev p-4 py-1 bg-emerald-500 rounded-md">
								<span class="text-2xl" aria-hidden="true">«</span>
								<span class="sr-only">Previous</span>
							</button>
							<button type="button" class="hs-carousel-next p-4 py-1 bg-emerald-500 rounded-md">
								<span class="sr-only">Next</span>
								<span class="text-2xl" aria-hidden="true">»</span>
							</button>
						</div>
						</div>

					
				{% comment %}info section{% endcomment %}
				<div class="flex flex-col mb-2">
					<div
						class="capitalize flex justify-start items-center gap-x-1 font-medium text-2xl"
					>
						<a
							class="hover:text-emerald-500 transition-colors duration-200 flex gap-x-1 justify-start items-center font-header"
							href="{% url 'coach:shop' %}"
						>
							shop
							<span class="material-symbols-outlined text-3xl">chevron_right</span>
						</a>
						<a
							class="hover:text-emerald-500 transition-colors duration-200 font-header" 
							href="{% url 'coach:shop' %}?filter={{ product.type }}#products"
							>{{ product.type }}</a
						>
					</div>
					<h1 class="font-bold  capitalize text-4xl mt-3">{{ product.name }}</h1>
					<p
						id="product-price"
						data-price="{{product.price}}"
						class="text-2xl font-medium  tabular-nums mt-3"
					>
						${{ product.price }} 
					</p>
					<p class="mb-4 max-w-md text-base font-medium mt-3">
						{{ product.description }}
					</p>
					
					{% comment %}Quantity section{% endcomment %}
					<p class="mt-4 font-medium capitalize mb-2">quantity</p>
					<div class="flex items-center">
						<button
							class="border px-20 py-2 flex items-center text-lg font-bold border-neutral-50 hover:text-emerald-400 transition-colors duration-200 hover:border-emerald-400"
							id="add-quantity"
						>
							<span class="material-symbols-outlined text-2xl">add</span>
						</button>
						<input
							id="quantity-value"
							type="text"
							value="1"
							class="bg-transparent w-[100px] text-center text-xl outline-none border-none"
						/>
						<button
							class="border px-20 py-2 flex items-center text-lg font-bold border-neutral-50 hover:text-emerald-400 transition-colors duration-200 hover:border-emerald-400"
							id="minus-quantity"
						>
							<span class="material-symbols-outlined text-2xl">remove</span>
						</button>
					</div>
					<button
						data-add-to-cart-btn
						data-product-id="{{product.id}}"
						class="font-semibold bg-emerald-500 hover:bg-black py-2 mt-6 w-full font-header text-2xl rounded-md hover:scale-[1.02] duration-300 hover:text-white"
						data-product-type="accessory"
					>
						add to cart
					</button>
				</div>
			</div>
			<div class="w-full max-w-[90%] mx-auto mt-28">
				<h3 class="text-2xl font-medium">More Products</h3>
				<h1 class="text-5xl thick-font font-bold">For You</h1>
				<div class="w-full py-16 h-fit embla after:pointer-events-none before:pointer-events-none relative after:absolute after:right-0 after:top-0 after:h-full after:w-11 after:bg-gradient-to-l mx-auto items-center">
					<div class="embla__container flex">
						{% for p in popular_products %}
						<a href="{% url 'coach:products' id=p.id %}" class="mr-12 embla__slide flex-shrink-0 flex-grow-0 basis-auto w-full max-w-[320px] bg-emerald-900 rounded-[36px] flex flex-col items-center p-3" >
							<img
								src="{{MEDIA_URL}}{{p.url}}"
							  class="rounded-3xl w-full object-top mb-1 min-h-[300px] object-cover"
							/>
							  <div class="mt-2 w-full flex items-center justify-center gap-x-4">
								  <div class="mb-2">
									<p class="text-emerald-300 font-medium capitalize ">
										{{p.name}}
									</p>
								  </div>
								</div>
								<div class="mb-2 mt-2">
								  <p class="text-emerald-300 thick-font text-2xl">${{p.price}}</p>
								  
								</div>
								
						</a>
						{% endfor %}
					</div>
				</div>
			</div>


	
			
            
		</main>

		
		{% include 'coach/componants/footer.html' %}

		<script src="https://unpkg.com/embla-carousel/embla-carousel.umd.js"></script>
		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
		<script  src="{% static 'coach/slider.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@preline/carousel@2.1.0/index.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.8.1/vanilla-tilt.min.js" integrity="sha512-wC/cunGGDjXSl9OHUH0RuqSyW4YNLlsPwhcLxwWW1CR4OeC2E1xpcdZz2DeQkEmums41laI+eGMw95IJ15SS3g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
		<script src="{% static 'coach/quantity.js' %}"></script>
		<script
			type="module"
			src="{% static 'coach/add-to-cart.mjs' %}"
		></script>
		<script src="{% static 'coach/navDropDown.js' %}"></script>
	</body>
</html>

coaching/coach/templates/coach/shop.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,200"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'coach/nav.css' %}" />
    <link rel="stylesheet" href="{% static 'coach/global.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body class="bg-gray-300 ">
    {% include 'coach/componants/nav.html' %}
    <main class="min-h-screen">
      <section
        id="products"
        class="w-full gap-y-5 mt-[6rem] mb-10 flex flex-col justify-center items-center"
      >
        <h1 class="text-center p-1 text-3xl font-header">
          Filter By Categories:
        </h1>
        <div
          class="w-full flex justify-center font-medium gap-x-7 items-center mx-auto"
        >
          <a
            href="{% url 'coach:shop' %}#products"
            class="{% if filter == '' %}bg-gradient-to-bl from-emerald-500 to-black border-neutral-50 text-neutral-50 {% else %} hover:bg-emerald-600 hover:text-neutral-50 hover:border-emerald-400 text-neutral-600 bg-neutral-300 border-neutral-400 {% endif %} duration-300 transition-colors px-6 py-2 border capitalize rounded-full w-full max-w-[104px] text-center"
            >all</a
          >
          <a
            href="{% url 'coach:shop' %}?filter=dumbelle#products"
            class="{% if filter == 'dumbelle' %}bg-gradient-to-bl from-emerald-500 to-black border-neutral-50 text-neutral-50 {% else %} hover:bg-emerald-600 hover:text-neutral-50 hover:border-emerald-400 text-neutral-600 bg-neutral-300 border-neutral-400 {% endif %} flex duration-300 transition-colors px-6 py-2 border capitalize rounded-full w-fit text-center"
            >dumbelle</a
          >
          <a
            href="{% url 'coach:shop' %}?filter=weight#products"
            class="{% if filter == 'weight' %}bg-gradient-to-bl from-emerald-500 to-black border-neutral-50 text-neutral-50 {% else %} hover:bg-emerald-600 hover:text-neutral-50 hover:border-emerald-400 text-neutral-600 bg-neutral-300 border-neutral-400 {% endif %} duration-300 transition-colors px-6 py-2 border capitalize rounded-full text-center"
            >weight</a
          >
          <a
            href="{% url 'coach:shop' %}?filter=iron bar#products"
            class="{% if filter == 'iron bar' %}bg-gradient-to-bl from-emerald-500 to-black border-neutral-50 text-neutral-50 {% else %} hover:bg-emerald-600 hover:text-neutral-50 hover:border-emerald-400 text-neutral-600 bg-neutral-300 border-neutral-400 {% endif %} duration-300 transition-colors px-6 py-2 border capitalize rounded-full text-center"
            >iron bar</a
          >
        </div>
      </section>

      <div
        class="relative bg-white flex px-1 py-1 rounded-full border border-emerald-500 overflow-hidden max-w-md mx-auto font-[sans-serif]"
      >
        <input
          type="text"
          id="searchInput"
          placeholder="Search Something..."
          class="w-full outline-none bg-white pl-4 text-sm"
        />
        <button
          id="searchButton"
          type="submit"
          class="bg-emerald-500 hover:bg-black transition-all text-white text-sm rounded-full px-5 py-2.5"
        >
          Search
        </button>
      </div>
      <div
        id="product_container" class="w-full max-w-[1000px] grid grid-cols-3 gap-y-2 gap-x-11 content-center mt-10 mx-auto"
      >
        {% for p in products %}
        <a
          href="{% url 'coach:products' id=p.id %}"
          class="w-full max-w-[320px] bg-emerald-900 rounded-[36px] flex flex-col items-center p-3"
        >
          <img
            src="{{MEDIA_URL}}{{p.url}}"
            class="rounded-3xl w-full object-top mb-1 min-h-[300px] object-cover"
          />
          <div class="mt-2 w-full flex items-center justify-center gap-x-4">
            <div class="mb-2">
              <p class="text-emerald-300 font-medium capitalize">{{p.name}}</p>
            </div>
          </div>
          <div class="mb-2 mt-2">
            <p class="text-emerald-300 thick-font text-2xl">{{p.price}} $</p>
          </div>
        </a>
        {% endfor %}
      </div>
    </main>
    {% include 'coach/componants/footer.html' %}
    <script type="module">
      import preline from "https://cdn.jsdelivr.net/npm/preline@2.1.0/+esm";
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@preline/accordion@2.1.0/index.min.js"></script>
    <script src="{% static 'coach/search.mjs' %}" type="module"></script>
    <script src="{% static 'coach/navDropDown.js' %}"></script>
    
    
  </body>
</html>

coaching/coach/templates/coach/stats.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'coach/global.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="{% static 'coach/chart.css' %}"/>
    <link
      href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@200;400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,600,0,200"
    />
    <link
      href="https://api.fontshare.com/v2/css?f[]=clash-display@400,500,700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body class="bg-emerald-100 w-full h-full">
    {% include 'coach/componants/coach_sidebar.html' %}

    <h1
      class="text-4xl capitalize font-bold w-full mt-12 mb-10 max-w-[1350px] mx-auto text-emerald-900 thick-font"
    >
      coach statistics
    </h1>

    <div
      class="grid grid-cols-[730px,630px] grid-rows-[520px,530px] justify-center justify-items-center mx-auto w-full gap-x-4 gap-y-4"
    >


    <div class="bg-emerald-950 col-[1/3] w-full  overflow-hidden relative rounded-[48px] p-8">
      <img
        src="{% static 'img/Ellipse 1.svg' %}"
        class="absolute right-[-300px] top-[-303px] max-w-[700px] isolate -z-1"
      />
      <div
        class="flex justify-center border isolate backdrop-blur-md border-emerald-900 p-8 rounded-3xl items-center gap-x-4"
      >
        
          <div id="chart"></div>
        </div>
      </div>



      <div class="col-[1/3] row-[2/3] w-full bg-emerald-950 overflow-hidden relative rounded-[48px] p-8">
        <img
          src="{% static 'img/Ellipse 1.svg' %}"
          class="absolute right-[2px] top-[-400px] max-w-[700px] isolate -z-1"
        />
        <img
        src="{% static 'img/Ellipse 1.svg' %}"
        class="absolute right-[927px] top-[200px] max-w-[700px] isolate -z-1"
      />
        <div
          class="flex justify-center border isolate backdrop-blur-md border-emerald-900 p-8 rounded-3xl items-center gap-x-4"
        >
          
            <div id="chart2"></div>
          </div>
        </div>
        
        
    </div>

    <script src="{% static 'coach/chart.mjs' %}" type="module"></script>
  </body>
</html>