coaching/coach/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.contrib import admin

app_name = "coach"

urlpatterns = [
    path("", views.home, name="home"),
    
    path("signin", views.signin, name="signin"),
    path("signup", views.signup, name="signup"),
    path("logout", views.sign_out, name="logout"),

    path("session", views.session, name="session"),
    path('products/', views.session_filtre, name='session_filtre'),
    path("shop", views.shop, name="shop"),
    path("products/<int:id>", views.products, name="products"),
    path('products_list', views.product_list, name='product_list'),
    

    path("session_creation", views.session_creation, name="session_creation"),
    path("update_session", views.update_session, name="update_session"),
    path("addimg", views.add_session, name="addimg"),
    path("updateimg", views.update_session_img, name="updateimg"),


    path("cart", views.cart, name="cart"),
    path(
        "cart/update_item_quantity",
        views.update_item_quantity,
        name="update_item_quantity",
    ),
    path("cart/add_to_cart", views.add_to_cart, name="add_cart_item"),
    path(
        "cart/add_order",
        views.add_order_handler,
        name="add_order",
    ),
    path(
        "cart/delete_cart_item", views.delete_cart_item_handler, name="delete_cart_item"
    ),
    path("add_to_cart_popup/<int:session_id>/", views.pop_up, name="add_to_cart_popup"),
    path("reviews/<int:session_id>/", views.reviews, name="reviews"),
    path("comments/<int:session_id>/", views.get_sessions_reviews, name="comments"),


    path("dashboard", views.dashboard, name="dashboard"),
    path("delete-session/<int:session_id>/", views.delete_session, name="delete_session"),
    path("stats", views.stats, name="stats"),
    path("stats/participent_by_coach", views.participent_by_coach, name="participent_by_coach"),
    path("stats/revenue_by_session", views.revenue_by_session, name="revenue_by_session"),
    path("stats/top_sessions", views.top_sessions, name="top_sessions"),
    path("profile", views.profile, name="profile"),
    path("profile/coach_request", views.coach_request, name="coach_request"),
    path("delete-session-order/<int:order_id>/", views.delete_session_order, name="delete_order_session"),
]


# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coaching/coaching/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("coach.urls")),
]

coaching/coach/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

import random

def generate_random_id():
    return random.randint(10000, 99999)  # Adjust the range as needed



class Profile(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/',default="profile2.png")

    class Type(models.TextChoices):
        Client = 'client'
        Coache = 'coach'

    def __str__(self):
        return f"{self.type} - id {self.id}"
    type = models.CharField(max_length=7, choices=Type.choices, default=Type.Client)


class session_location(models.Model):
    id = models.AutoField(primary_key=True)
    location = models.CharField(max_length=100, null=True)
    


class Training_session(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True)
    small_sum = models.CharField(max_length=100, null=True)
    categorie = models.CharField(max_length=100, null=True)
    type = models.CharField(max_length=100, null=True)
    description = models.JSONField( null=True)
    price = models.DecimalField( max_digits=5, decimal_places=2, null=True)
    Profile = models.ForeignKey(Profile, on_delete=models.CASCADE,default=1) 
    img = models.ImageField(upload_to="sessions/%y/%m/%d", null=True)
    start_time = models.TimeField(null=True)    
    end_time = models.TimeField(null=True)   
    participant_limit = models.IntegerField(null=True)
    location = models.ForeignKey(session_location,default='1', on_delete=models.CASCADE)

class categorie(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True)

    
    
    
    
class session_date(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateField(null=True)
    session = models.ForeignKey(Training_session, on_delete=models.CASCADE)

    

class Reviews(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    session = models.ForeignKey(Training_session, on_delete=models.CASCADE)
    stars = models.IntegerField()
    comment = models.TextField(blank=True, null=True)
    title = models.TextField(blank=True, null=True)




class Product(models.Model):
    id = models.AutoField(primary_key=True)
    description = models.TextField(null=True)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=50, null=True)

    def __str__(self):
        return f"{self.name} - Id {self.id}"

class ProductImages(models.Model):
    id = models.AutoField(primary_key=True)
    urls = models.ImageField(upload_to="products/%y/%m/%d")
    type = models.CharField(max_length=50)

    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    #convertir un objet en chaîne de caractères
    def __str__(self):
        return f"{self.product.name} - Image {self.urls}"

class ProductVariant(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    product = models.ForeignKey("Product", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name} - Variant {self.id}"

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    address = models.TextField()
    order_total = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart_name = models.CharField(max_length=255)
    exp = models.DateField()
    cvv = models.CharField(max_length=4)
    

    def __str__(self):
        return f"Order {self.id} - {self.first_name} {self.last_name} - Total: {self.order_total}"

class OrderToProduct(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey("Order", on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.SET_NULL,related_name='orders_product', null=True, blank=True)
    training_session = models.ForeignKey("Training_session",related_name='orders_training_session',on_delete=models.CASCADE, null=True, blank=True)
    product_name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    price=models.DecimalField(max_digits=10, decimal_places=2, default=0)
    type = models.CharField(max_length= 255, default="session")
    date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return f"Order {self.order_id} - {self.product_name} - Quantity {self.quantity}"

class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)



    def __str__(self):
        return f"Cart {self.id} - Total: {self.total}"

class CartItem(models.Model):
    id = models.AutoField(primary_key=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    cart_id = models.ForeignKey("Cart", on_delete=models.CASCADE)
    product = models.ForeignKey("Product",on_delete=models.SET_NULL, null=True, blank=True)
    training_session = models.ForeignKey("Training_session",on_delete=models.SET_NULL, null=True, blank=True)
    type = models.CharField(max_length= 255, default="session")

    #chose what to display in admin 
    def __str__(self):
        return f"CartItem {self.id} - Quantity: {self.quantity} - Price: {self.price}"
    

class CoachRequest(models.Model):
    id = models.AutoField(primary_key=True)
    exp = models.CharField(max_length= 255, default="1")
    description= models.CharField(max_length= 255, default="")
    Profile = models.ForeignKey(Profile, on_delete=models.CASCADE,default=1) 
    
    def __str__(self):
        return f"REQUEST {self.id} - experience: {self.exp}"

coaching/coach/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Training_session,Profile,CoachRequest


class SigninForm(forms.Form):
        email = forms.EmailField(required=True)
        password = forms.CharField(max_length=50)  
        

class SignupForm(UserCreationForm):
    firstname = forms.CharField(max_length=50)
    lastname = forms.CharField(max_length=50)
    email=forms.EmailField(required=True)
    class Meta:
        model=User
        fields=['username','email','password1','password2']
    def save(self, commit=True):
        user = super(SignupForm , self).save(commit=False)
        user.first_name = self.cleaned_data["firstname"]
        user.last_name = self.cleaned_data["lastname"]
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]

        if commit:
            print("user-commit")
            print(user)
            user.save()
        return user
    
class ImageForm(forms.ModelForm):
    class Meta:
        model = Training_session        
        fields = ['Profile', 'img']  # Include 'user' field in the form
    
          
class sessionform(forms.ModelForm):
    class Meta:
        model = Training_session        
        fields = ['description', 'name', 'start_time', 'end_time']  # Include 'user' field in the form


    # id = models.AutoField(primary_key=True)
    # name = models.CharField(max_length=100, null=True)
    # description = models.CharField(max_length=100, null=True)
    # Profile = models.ForeignKey(Profile, on_delete=models.CASCADE) 
    # img = models.ImageField(upload_to="sessions/%y/%m/%d", null=True)
    # start_time = models.DateTimeField(null=True)    
    # end_time = models.DateTimeField(null=True)   
    # location = models.CharField(max_length=100,null=True)
    # participant_limit = models.IntegerField(null=True) 

class FilterForm(forms.Form):
    PRICE_CHOICES = [
        ('under_25', 'Under $25'),
        ('25_to_50', '$25 to $50'),
        ('50_to_100', '50 to $100'),
        ('over_100', 'Over $100'),
    ]
    SORT_CHOICES = [
        ('popularity', 'Popularity'),
        ('high_to_low', 'Price: High to Low'),
        ('low_to_high', 'Price: Low to High'),
    ]
    SESSION_TYPE_CHOICES = [
        ('Personal', 'Personal'),
        ('Group', 'Group'),
    ]
    
    price_range = forms.ChoiceField(
        choices=PRICE_CHOICES,
        widget=forms.RadioSelect,
        required=False
    )
    sort_by = forms.ChoiceField(
        choices=SORT_CHOICES,
        widget=forms.RadioSelect,
        required=False
    )
    session_type = forms.ChoiceField(
        choices=SESSION_TYPE_CHOICES,
        widget=forms.RadioSelect,
        required=False
    )


class Editprofileform(forms.ModelForm):

    class Meta:
        model=User
        fields=['first_name','last_name']

class Editimageprofileform(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        
        
class coach_request_form(forms.ModelForm):
    class Meta:
        model = CoachRequest
        fields = ['exp','description','Profile']

coaching/coach/views.py
from coach.api.sign_up import signup
from coach.api.home import home
from coach.api.sign_in import signin
from coach.api.logout import sign_out
from coach.api.session import session
from coach.api.shop import shop
from coach.api.products import products
from coach.api.training_session.create_session import add_session,update_session_img
from coach.api.update_session import update_session
from coach.api.productslist import product_list
from coach.api.cart import cart
from coach.api.add_to_cart import add_to_cart
from coach.api.dashboard import dashboard
from coach.api.session_creation import session_creation
from coach.api.delete_cart_item import delete_cart_item_handler
from coach.api.add_order import add_order_handler
from coach.api.profile import profile,coach_request
from coach.api.stats import stats,participent_by_coach,revenue_by_session,top_sessions
from coach.api.session_filtrage import session_filtre
from coach.api.add_to_cart_popup import pop_up
from coach.api.reviews import reviews,get_sessions_reviews
from coach.api.update_item_quantity import update_item_quantity
from coach.api.delete_session_order import delete_session_order

from coach.api.delete_session import delete_session

coaching/coach/templates/coach/componants/categorie.html
{% load static %}

<div class="w-full max-w-[960px] mx-auto my-24 p-[1px]">
    <h3 class="text-2xl font-medium">Classes Designed</h3>
    <h1 class="text-5xl font-header w-fit">For You</h1>
    <div class="flex gap-x-2 px-2 justify-between items-center ">
      <div class="py-14">
        <img class="rounded-3xl w-52" src=" {% static 'img/coach007.jpg' %}" />
        <div class="flex justify-between items-center pt-2 px-2">
          <p class="text-sm font-medium">Personal Training</p>
          <a href="http://127.0.0.1:8000/session?allow_filter=true&session_type=Personal"
            class="bg-green-400 rounded-full flex items-center justify-center size-8"
          >
          <span class="material-symbols-rounded">
            north_east
            </span>
          </a>
        </div>
      </div>
      <div class="self-end">
        <img class="rounded-3xl w-52" src=" {% static 'img/Samba.jpg' %}" />
        <div class="flex justify-between items-center pt-2 px-2">
          <p class="text-sm font-medium">Samba Training</p>
          <a href="http://127.0.0.1:8000/session?allow_filter=true&category=Samba"
            class="bg-green-400 rounded-full flex items-center justify-center size-8 "
          >
          <span class="material-symbols-rounded">
            north_east
          </span>
          </a>
        </div>
      </div>
      <div class="self-center">
        <img class="rounded-3xl w-52" src=" {% static 'img/coach003.jpg' %}" />
        <div class="flex justify-between items-center pt-2 px-2">
          <p class="text-sm font-medium">Martial Art</p>
          <a href="http://127.0.0.1:8000/session?allow_filter=true&category=Martial+Art"
            class="bg-green-400 rounded-full flex items-center justify-center size-8">
            <span class="material-symbols-rounded">
                north_east
                </span>
        </a>
        </div>
      </div>
      <div class="self-start">
        <img class="rounded-3xl w-52" src=" {% static 'img/Waifu.jpg' %}" />
        <div class="flex justify-between items-center pt-2 px-2">
          <p class="text-sm font-medium">Group Training</p>
          <a href="http://127.0.0.1:8000/session?allow_filter=true&session_type=Group"
            class="bg-green-400 rounded-full flex items-center justify-center size-8"
          >
          <span class="material-symbols-rounded">
            north_east
            </span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

coaching/coach/templates/coach/componants/coach_sidebar.html
<div class="h-1 w-[60px] col-[1/2]"></div>  
  

<section class="bg-emerald-950 flex flex-col fixed justify-evenly gap-y-9 top-1/2 -translate-y-1/2 left-2 rounded-full py-6 overflow-hidden p-2">
    
                    
    <a  href="{% url 'coach:dashboard' %}" class="flex flex-col items-center justify-center transition-colors duration-500 text-emerald-300 text-center text-sm py-2 px-2  hover:bg-emerald-800/30 rounded-2xl"><span class="  text-3xl text-emerald-300  material-symbols-outlined">
        space_dashboard
        </span>hub
        {% if request.path == '/dashboard' %}
        <p class=" rounded-full bg-emerald-500 group-hover:bg-emerald-200 size-2 mt-1">
        </p>
        {% endif %}
    </a>


    <a href="{% url 'coach:home' %}" class="flex flex-col items-center group transition-colors duration-500 justify-center text-emerald-300 text-center text-sm  py-2 px-2 hover:bg-emerald-800/30 rounded-2xl"><span class="  text-3xl text-emerald-300 material-symbols-outlined">
                    home
                    </span>home    
    </a>
               
                

    <a  href="{% url 'coach:session_creation' %}" class="flex flex-col items-center justify-center transition-colors duration-500 text-emerald-300 text-center text-sm py-2 px-2  hover:bg-emerald-800/30 rounded-2xl"><span class="  text-3xl text-emerald-300  material-symbols-outlined">
                    exercise
    </span>session</a>
                    
                    
    <a  href="{% url 'coach:stats' %}" class="flex flex-col items-center transition-colors duration-500 justify-center text-emerald-300 text-center text-sm hover:bg-emerald-800/30 rounded-2xl py-2 px-2 "><span class="  text-3xl text-emerald-300  material-symbols-outlined">
                    equalizer
                    </span>stats
                    {% if request.path == '/stats' %}
                    <p class=" rounded-full bg-emerald-500 group-hover:bg-emerald-200 size-2 mt-1">
                    </p>
                    {% endif %}
    </a>

                    
                


</section>

coaching/coach/templates/coach/componants/cta.html
{% load static %}

<div class="flex justify-evenly items-center gap-x-4 flex-wrap max-w-[960px] mx-auto mt-[150px]">
<div class="flex">
  <img
    class="rounded-xl w-full mr-4 max-w-28 object-cover"
    src="{% static 'img/coach003.jpg' %}"
  />
  <img class="rounded-xl w-52" src=" {% static 'img/Waifu.jpg' %}" />
</div>
<div class="flex flex-col max-w-96">
  <p class="text-3xl font-medium">Are You Looking For A Coach</p>
  <p class="mt-1 font-medium">
    Looking for a change? A coach can be your compass. Navigate toward
    your goals, one step at a time. With tailored support, you'll thrive
    and reach new heights.
  </p>
  <a href="{% url 'coach:session' %}" class="bg-green-400 rounded-full text-sm p-2 font-medium px-4 mt-6 text-center">
    EXPLORE MORE
  </a>
</div>
</div>

coaching/coach/templates/coach/componants/footer.html
<footer class="w-full mt-28 pb-14 bg-emerald-300 rounded-t-3xl">
	<div
		class="flex justify-between items-start w-full max-w-[1200px] mx-auto mt-14 p-5"
	>
		<div class="text-left">
			<h2 class="text-emerald-800 font-medium text-lg mb-2">Conquer</h2>
			<p class="text-neutral-900 text-sm font-medium">
				this project was build by a third party, the nazi regime<br />
				equipment and supplements.
			</p>
			<p class="mt-4 text-neutral-900 text-sm font-medium">
				Copyright ©2023 Ecommerce by Conquer group.
			</p>
		</div>
		<div class="ml-auto">
			<h2 class="text-emerald-800 font-medium text-lg mb-2">Contact us</h2>
			<p class="text-neutral-900 text-sm mb-2 font-medium">address · tanger tren city</p>
			<p class="text-neutral-900 text-sm mb-2 font-medium">email · help@Conquer.com</p>
			<p class="text-neutral-900 text-sm mb-2 font-medium">phone · 0612365478</p>
		</div>
	</div>
</footer>

coaching/coach/templates/coach/componants/nav.html
<nav class="nav fixed w-full bg-emerald-950/80 backdrop-blur-md top-2 z-10 rounded-full max-w-4xl left-1/2 -translate-x-1/2 px-4 py-4 shadow-md">
    <div class="text-red-500 font-medium">
        <a href="{% url 'coach:home' %}">
            <div id="logo" class="text-emerald-300 thick-font"><p class="capitalize">Conquer</p></div>
        </a>
    </div>
    <div class="flex text-white items-center list-none gap-x-4 ">
        <li><a href="{% url 'coach:shop' %}" class="here hover:text-emerald-300">accessory</a></li>
        <li><a href="{% url 'coach:session' %}" class="here hover:text-emerald-300">sessions</a></li>
        {% if user.profile.type == 'coach' %}
            <li><a href="{% url 'coach:dashboard' %}" class="here hover:text-emerald-300">dashboard</a></li>
        {% endif %}
    </div>
    <div class="text-slate-50">
      <ul class="nav_links items-center flex justify-between"> 

       
        {% if user.is_authenticated %} 
        <li class="relative">
            <button data-nav-dropdown-btn class="group font-semibold inline-flex justify-center items-center gap-x-1  bg-white/5 p-1 py-2 rounded-lg">
                <span class="material-symbols-outlined group-hover:text-emerald-300 transition-colors duration-300 text-lg leading-none"> account_circle</span>
                <span class="material-symbols-outlined group-hover:text-emerald-300 transition-colors duration-300 text-lg leading-none">expand_more</span>
            </button>

            <ul  data-nav-dropDown-list class="invisible opacity-0  w-fit transition-opacity duration-200 top-[calc(100%+1.5rem)] rounded-lg left-1/2 -translate-x-1/2 text-neutral-50 absolute bg-emerald-950/80 ">
                <li data-nav-dropDown-item class="w-36 m-2 p-2  transition-colors duration-300 rounded-lg cursor-pointer font-medium">
                    <a class="flex items-center justify-between  gap-x-2 w-full" href="{% url 'coach:cart' %}"  >cart
                        <span class="material-symbols-outlined  text-lg  leading-none">
                            shopping_cart
                            </span></a>
                </li>

                <li data-nav-dropDown-item class="w-36 m-2 p-2  transition-colors duration-300 rounded-lg cursor-pointer font-medium">
                    <a class="flex items-center justify-between  gap-x-2 w-full"  href="{% url 'coach:profile' %}">profile
                        <span class="material-symbols-outlined  text-lg  leading-none"> account_circle</span>
                        </a>
                </li>
                <li data-nav-dropDown-item class="w-36 m-2 p-2  transition-colors duration-300 rounded-lg cursor-pointer font-medium">
                    <a class="flex items-center  justify-between gap-x-2 w-full" href="{% url 'coach:logout' %}" >sign out
                        <span class="material-symbols-outlined  text-lg leading-none ">account_circle</span>
                    
                        </a>
                </li>
            </ul>
        </li>

        {% else  %}
        <li>
            <a class="flex items-center gap-x-2" href="{% url 'coach:signin' %}" >sign in
            </a>
        </li>
        {% endif  %} 
        
        
    </div>
</nav>

coaching/coach/templates/coach/componants/weekly_popular_sessions.html
{% load static %}


<div
  class="w-full mx-auto max-w-[97%] flex flex-col bg-primary min-h-screen rounded-[36px] my-[150px] overflow-hidden relative p-11 isolate"
>
  <img
    src="{% static 'img/Ellipse 1.svg' %}"
    class="absolute right-[677px] top-[480px] max-w-[700px] -z-10"
  />
  <img
    src="{% static 'img/Ellipse 1.svg' %}"
    class="absolute right-[-300px] top-[-200px] max-w-[700px] -z-10"
  />

  <div class="flex justify-between items-center">
    <div class="">
      <h3 class="text-2xl text-black font-medium uppercase">
        training sessions
      </h3>
      <h1 class="text-7xl thick-font font-bold text-black uppercase">
        join today
      </h1>
    </div>

    <p
      class="bg-emerald-900 text-primary-subtle px-6 py-3 rounded-full font-medium capitalize mb-3"
    >
      best plan of the week
    </p>
  </div>
  <div class="min-h-6 flex-grow flex gap-x-40 items-center justify-center">
    {% for session in sessions %}
    <a href="{% url 'coach:session' %}"
      class="w-full max-w-[320px] bg-emerald-900 rounded-[36px] flex flex-col items-center p-3"
    >
      <img
        src="{{MEDIA_URL}}{{session.img}}"
        class="rounded-3xl w-full object-top mb-4 min-h-[200px] object-cover"
      />
      <div class="min-w-0 max-w-full w-full">
        <h4
          class="thick-font text-lg capitalize text-center font-medium text-primary truncate"
        >
          {{session.name}}
        </h4>
      </div>
      <div class="flex w-full justify-center items-center gap-x-3">
        <p
          class="text-emerald-300 flex items-center justify-center gap-x-2 bg-emerald-800 rounded-full self-start px-2 font-medium capitalize"
        >
          <span class="material-symbols-outlined text-lg font-semibold">
            history_toggle_off
          </span>
          <span>{{ session.duration }}h</span>
        </p>
        <p
          class="text-emerald-300 flex items-center justify-center gap-x-2 bg-emerald-800 rounded-full self-start px-2 font-medium capitalize"
        >
          <span class="material-symbols-outlined"> groups </span>
          <span>{{ session.participant_limit }}</span>
        </p>
        <p
          class="text-emerald-300 flex items-center justify-center gap-x-2 bg-emerald-800 rounded-full self-start px-2 font-medium capitalize"
        >
          <span class="material-symbols-outlined"> star </span> <span>{{session.star_rating}}</span>
        </p>
      </div>

      <div class="mt-2 w-full flex items-center gap-x-4">
        <img
          class="size-12 rounded-full object-cover"
          src="{{MEDIA_URL}}{{session.coach_img}}"
        />
        <div class="mb-2">
          <p class="text-emerald-300">coach</p>
          <p class="text-emerald-300 font-medium capitalize">
            {{session.coach_first_name}} {{session.coach_last_name}}
          </p>
        </div>
      </div>
      <p
        class="text-emerald-300 flex items-center justify-center gap-x-2 bg-emerald-800 py-2 rounded-b-full mt-2 w-full self-start px-2 font-medium capitalize"
      >
        {{session.categorie}}
      </p>
    </a>
    {% endfor %}
  </div>
</div>



    